### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by austin1244** [austin1244/MI-449-SS17-740-html-terminal-and-git-_u9ftI#1]
@stuartpearman Can you take a look at this? It's [hosted here](https://austin1244.github.io/MI-449-SS17-740-html-terminal-and-git-_u9ftI/) and meets the following criteria:

- [x] A knock-knock joke is displayed when visiting the website
- [x] The code is pushed to GitHub
- [x] The website is hosted on GitHub Pages

**Comment by KatieMFritz** [comment]
Stealing this from Stuart. Everything looks great!
:shipit: 

PS Let me know if your project doesn't show up as approved in the msu.lansing.codes app. It should work even if a different reviewer approves it, but it's early days so you never know!

**Comment by KatieMFritz** [comment]
Testing again, because the webhook didn't work. 

:shipit:

**Comment by KatieMFritz** [comment]
Because of the bug that kept the repo from syncing with the msu.lansing.codes app, I made a copy of this issue at https://github.com/austin1244/MI-449-SS17-740-html-terminal-and-git-_u9ftI/issues/2.

Closing the original issue.
